disabled_rules:
- colon
- comma
- control_statement
opt_in_rules:
- empty_count
included:
- kenshu
excluded:
- Carthage
- Pods
- Source/ExcludedFolder
- Source/ExcludedFile.swift
force_cast: warning
force_try:
severity: warning
line_length: 110
type_body_length:
- 300 # warning
- 400 # error
file_length:
warning: 500
error: 1200
type_name:
min_length: 4
max_length:
warning: 40
error: 50
excluded: iPhone
identifier_name:
min_length:
error: 4
excluded:
- id
- URL
- GlobalAPIKey
reporter: "xcode"
